
nacos:
  config:
    server-addr: 188.131.169.24:8848
#    file-extension: yml
#    namespace: 8e188d50-6ef9-43b6-996e-3ea6ca27f3e9
#    group: test


#开启端点
# endpoint http://localhost:8080/actuator/nacos-config
# health http://localhost:8080/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always