# 服务名称
spring:
  application:
    name: test-springcloud-gateway
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: blog
#          url: http://blog.yuqiyu.com
#          predicates:
#            #匹配路径转发
#            - Path=/api-boot-datasource-switch.html
# Eureka Server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18001/eureka/
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug
