spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
#            defaultZone: http://localhost:10000/eureka/
      defaultZone: http://localhost:18001/eureka/

server:
  port: 9091
