#spring配置
spring:
  application:
    #应用名称
    name: service-registry

#服务器配置
server:
  #端口
  port: 9001

#服务中心发现注册配置
eureka:
  instance:
    #主机名称
    hostname: service-registry1
  client:
    #服务注册中心地址
    service-url:
      defaultZone:  http://service-registry2:9002/eureka,http://service-registry3:9003/eureka
    #服务注册中心相互注册一定要显示的设置register-with-eureka 和fetch-registry的值为true,否则会服务不可用
    register-with-eureka: true
    fetch-registry: true