server:
  port: 8080

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 188.131.169.24:8848
        namespace: 8e188d50-6ef9-43b6-996e-3ea6ca27f3e9